import type { QuoteAnalysisResponse, QuoteRankingItem } from '@/lib/types';

/**
 * Builds a plain-text, email-pasteable summary of a quote comparison report.
 *
 * The output is derived only from the deterministic comparison payload, so a
 * copied summary always matches the figures shown on screen. It is intended for
 * pasting into an approval email, a Slack thread, or a spreadsheet note.
 */

function formatMoney(amount: number | null, currency: string | null): string {
  if (amount === null) {
    return 'Not extracted';
  }

  if (!currency) {
    return amount.toLocaleString('en-US', { maximumFractionDigits: 2 });
  }

  try {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency,
      maximumFractionDigits: 2,
    }).format(amount);
  } catch {
    return `${amount.toLocaleString('en-US')} ${currency}`;
  }
}

function basisLabel(basis: QuoteRankingItem['basis']): string {
  if (basis === 'weighted_unit_price') return 'weighted unit price';
  if (basis === 'reported_total_per_unit') return 'reported total / quantity';
  if (basis === 'reported_total') return 'reported total';
  return 'insufficient data';
}

function modeLabel(mode: QuoteAnalysisResponse['mode']): string {
  if (mode === 'demo') return 'Demo mode (no user files analyzed)';
  if (mode === 'partial') return 'Partial live analysis';
  return 'Live analysis';
}

function comparabilityLabel(
  comparability: QuoteAnalysisResponse['comparison']['comparability'],
): string {
  if (comparability === 'high') return 'High';
  if (comparability === 'limited') return 'Limited';
  return 'Insufficient';
}

type ComparableRow = QuoteRankingItem & { amount: number };

/** Comparable ranking rows (numeric amount), best value first. */
function comparableRows(ranking: QuoteRankingItem[]): ComparableRow[] {
  return ranking
    .filter((row): row is ComparableRow => typeof row.amount === 'number')
    .slice()
    .sort((a, b) => a.amount - b.amount);
}

export function buildQuoteSummaryText(result: QuoteAnalysisResponse): string {
  const { comparison } = result;
  const rows = comparableRows(comparison.ranking);
  const best = rows[0];
  const worst = rows[rows.length - 1];
  const singleCurrency =
    rows.length > 1 && new Set(rows.map((row) => row.currency)).size === 1;
  const savings =
    singleCurrency && best && worst ? worst.amount - best.amount : null;
  const savingsPercent =
    savings !== null && worst && worst.amount > 0
      ? Math.round((savings / worst.amount) * 100)
      : null;

  const lines: string[] = [];

  lines.push('SUPPLIER QUOTE COMPARISON — SourcingLab USA');
  lines.push('='.repeat(46));
  lines.push(`Analysis mode: ${modeLabel(result.mode)}`);
  lines.push(
    `Comparability: ${comparabilityLabel(comparison.comparability)} ` +
      `(${rows.length} of ${comparison.ranking.length} directly comparable)`,
  );
  if (comparison.priceSpreadPercent !== null) {
    lines.push(`Price spread: ${comparison.priceSpreadPercent}%`);
  }

  if (best) {
    lines.push('');
    lines.push('BEST COMPARABLE VALUE');
    lines.push(
      `${best.supplierName ?? 'Unidentified supplier'} — ` +
        `${formatMoney(best.amount, best.currency)} (${basisLabel(best.basis)})`,
    );
    if (savings !== null && savings > 0) {
      const pct = savingsPercent !== null ? ` (${savingsPercent}%)` : '';
      lines.push(
        `Potential savings vs highest quote: ${formatMoney(savings, best.currency)}${pct}`,
      );
    }
  }

  lines.push('');
  lines.push('RANKING');
  for (const item of comparison.ranking) {
    const rank = item.rank === null ? 'n/a' : `#${item.rank}`;
    lines.push(
      `${rank}  ${item.supplierName ?? 'Unidentified supplier'} — ` +
        `${formatMoney(item.amount, item.currency)} (${basisLabel(item.basis)})`,
    );
  }

  if (comparison.summary) {
    lines.push('');
    lines.push('SUMMARY');
    lines.push(comparison.summary);
  }

  if (comparison.vigilancePoints.length > 0) {
    lines.push('');
    lines.push('ITEMS TO VERIFY');
    for (const point of comparison.vigilancePoints) {
      lines.push(`- ${point}`);
    }
  }

  if (comparison.recommendations.length > 0) {
    lines.push('');
    lines.push('NEXT ACTIONS');
    for (const recommendation of comparison.recommendations) {
      lines.push(`- ${recommendation}`);
    }
  }

  lines.push('');
  lines.push(
    'Generated by SourcingLab USA. Figures are deterministic; verify against the source documents before contracting.',
  );

  return lines.join('\n');
}
