import type {
  EmailGeneratorResult,
  HsCodeAnalysisResult,
  LandedCostResult,
  ProductSpecResult,
} from '@/lib/types';

/**
 * Plain-text, email-pasteable summaries for each tool report. Every builder
 * derives its text only from the on-screen result so a copied summary always
 * matches what the user sees, and demo/estimate results stay clearly labeled.
 */

function bulletList(items: string[]): string[] {
  return items.map((item) => `- ${item}`);
}

export function buildProductSpecSummaryText(result: ProductSpecResult): string {
  const lines: string[] = [];

  lines.push('PRODUCT SPECIFICATION — SourcingLab USA');
  lines.push('='.repeat(42));
  lines.push(`Source: ${result.sourceLabel}`);
  if (result.mode === 'demo') {
    lines.push('Mode: Demo data — no AI analysis was performed.');
  }
  lines.push(`Product: ${result.productTitle}`);
  lines.push(`Target market: ${result.targetMarket}`);
  if (result.specsSummary) {
    lines.push('');
    lines.push(result.specsSummary);
  }

  lines.push('');
  lines.push('MATERIALS & DIMENSIONS');
  lines.push(`- Materials: ${result.technicalSpecs.materials.join(', ')}`);
  lines.push(`- Dimensions: ${result.technicalSpecs.dimensions}`);
  lines.push(`- Weight: ${result.technicalSpecs.weight}`);
  lines.push(`- Tolerances: ${result.technicalSpecs.tolerances}`);

  lines.push('');
  lines.push('REQUIREMENTS TO VERIFY');
  lines.push(...bulletList(result.certifications.toVerify));
  lines.push(`Notice: ${result.certifications.verificationNotice}`);

  lines.push('');
  lines.push('PRICING & MOQ TARGETS');
  lines.push(`- Target factory FOB: ${result.pricingTarget.estimatedFob}`);
  lines.push(`- Estimated landed cost: ${result.pricingTarget.targetLandCost}`);
  lines.push(
    `- Recommended MOQ: ${result.moq.recommended} ${result.moq.unit}`,
  );
  lines.push(`- Suggested MSRP: ${result.pricingTarget.recommendedMSRP}`);

  if (result.qualityControl.length > 0) {
    lines.push('');
    lines.push('QUALITY CONTROL CHECKPOINTS');
    lines.push(...bulletList(result.qualityControl));
  }

  lines.push('');
  lines.push(
    'Generated by SourcingLab USA. A draft specification — verify all commercial and regulatory details before use.',
  );

  return lines.join('\n');
}

const SHIPPING_MODE_TEXT: Record<
  LandedCostResult['calculationContext']['shippingMode'],
  string
> = {
  sea_fcl: 'Sea freight (FCL)',
  sea_lcl: 'Sea freight (LCL)',
  air_express: 'Air express',
  air_freight: 'Air freight',
};

export function buildLandedCostSummaryText(result: LandedCostResult): string {
  const money = (value: number) => `$${value.toLocaleString('en-US')}`;
  const context = result.calculationContext;
  const lines: string[] = [];

  lines.push('LANDED COST ESTIMATE — SourcingLab USA');
  lines.push('='.repeat(41));
  lines.push(`Destination: ${context.destinationMarket}`);
  lines.push(`Shipping mode: ${SHIPPING_MODE_TEXT[context.shippingMode]}`);
  lines.push(`HS code: ${context.hsCode} (duty ${context.customsDutyRate}%)`);

  lines.push('');
  lines.push('HEADLINE');
  lines.push(`- Landed cost / unit: ${money(result.unitLandedCost)}`);
  lines.push(`- Gross margin / unit: ${money(result.marginPerUnit)}`);
  lines.push(`- Margin: ${result.marginPercent}% • ROI: ${result.roiPercent}%`);

  lines.push('');
  lines.push('TOTALS');
  lines.push(`- Total investment: ${money(result.totalLandedCost)}`);
  lines.push(`- Factory cost: ${money(result.factoryCostTotal)}`);
  lines.push(`- Freight: ${money(result.freightCostTotal)}`);
  lines.push(
    `- Insurance${context.insuranceWasEstimated ? ' (estimated)' : ''}: ${money(result.insuranceCostTotal)}`,
  );
  lines.push(`- Calculated duties: ${money(result.customsDutyTotal)}`);

  lines.push('');
  lines.push('COST BREAKDOWN');
  lines.push(`- Factory: ${result.breakdownPct.factoryPct}%`);
  lines.push(`- Freight: ${result.breakdownPct.freightPct}%`);
  lines.push(`- Duties: ${result.breakdownPct.dutyPct}%`);
  lines.push(`- Other: ${result.breakdownPct.localPct}%`);

  if (result.warnings.length > 0) {
    lines.push('');
    lines.push('ITEMS TO VERIFY');
    lines.push(...bulletList(result.warnings));
  }

  lines.push('');
  lines.push(
    'Generated by SourcingLab USA. Deterministic estimate from your inputs; taxes and product-specific surcharges may not be included.',
  );

  return lines.join('\n');
}

export function buildHsCodeSummaryText(result: HsCodeAnalysisResult): string {
  const lines: string[] = [];

  lines.push('HS CODE & DUTY RESEARCH — SourcingLab USA');
  lines.push('='.repeat(43));
  lines.push(`Source: ${result.sourceLabel}`);
  if (result.mode === 'demo') {
    lines.push('Mode: Limited demo data.');
  }
  lines.push(`Product: ${result.productDescription}`);
  lines.push(`Category: ${result.categoryName}`);
  lines.push(
    `Destination: ${result.destinationMarket} • Origin: ${result.originCountry}`,
  );

  lines.push('');
  lines.push('CANDIDATE CODES');
  lines.push(`- 6-digit: ${result.hsCode6Digit}`);
  lines.push(
    `- 10-digit (${result.destinationMarket === 'US' ? 'HTS' : 'TARIC'}): ${result.hsCode10Digit}`,
  );

  lines.push('');
  lines.push('DUTY COMPONENTS (ESTIMATE)');
  lines.push(`- Base duty: ${result.dutyRates.baseDutyPercent}%`);
  lines.push(`- Trade-remedy / Section 301: ${result.dutyRates.section301Percent}%`);
  lines.push(`- Additional fees / taxes: ${result.dutyRates.additionalTaxesPercent}%`);
  lines.push(`- Component total: ${result.dutyRates.effectiveDutyPercent}%`);

  if (result.dutyBreakdownNotes.length > 0) {
    lines.push('');
    lines.push('CALCULATION NOTES');
    lines.push(...bulletList(result.dutyBreakdownNotes));
  }

  if (result.regulatoryWarnings.length > 0) {
    lines.push('');
    lines.push('IMPORT WARNINGS & REQUIREMENTS');
    lines.push(...bulletList(result.regulatoryWarnings));
  }

  if (result.alternativeHsCodes.length > 0) {
    lines.push('');
    lines.push('ALTERNATIVE CODES TO REVIEW');
    for (const alternative of result.alternativeHsCodes) {
      lines.push(
        `- ${alternative.code} — ${alternative.description} (${alternative.dutyRate})`,
      );
    }
  }

  lines.push('');
  lines.push(
    'Generated by SourcingLab USA. Codes and rates are starting points; verify current HTSUS/TARIC data with a customs professional.',
  );

  return lines.join('\n');
}

export function buildSupplierEmailSummaryText(
  result: EmailGeneratorResult,
): string {
  const lines: string[] = [];

  lines.push(`Subject: ${result.subject}`);
  lines.push('');
  lines.push(result.body);

  if (result.tips.length > 0) {
    lines.push('');
    lines.push('---');
    lines.push('REVIEW NOTES (not part of the email)');
    lines.push(...bulletList(result.tips));
  }

  return lines.join('\n');
}
